language: python
python:
  - "3.6"
  - "3.7"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - flake8
  - coverage run --source=questionnaire manage.py test
after_success:
  - coveralls