version: '3'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - .:/usr/src/appp
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres