# Generated by Django 2.2.8 on 2020-01-20 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('venue', models.CharField(max_length=250)),
                ('image_url', models.ImageField(null=True, upload_to='')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('event_type', models.CharField(choices=[('APPEARANCE_OR_SIGNING', 'Appearance or Signing'), ('ATTRACTION', 'Attraction'), ('CAMP_TRIP_RETREAT', 'Camp, Trip, or Retreat'), ('CLASS_TRAINING_WORKSHOP', 'Class, Training, or Workshop'), ('CONCERT_OR_PERFORMANCE', 'Concert or Performance'), ('CONFERENCE', 'Conference'), ('CONVENTION', 'Convention'), ('DINNER_OR_GALA', 'Dinner or Gala'), ('FESTIVAL_OR_FAIR', 'Festival or Fair'), ('GAME_OR_COMPETITION', 'Game or Competition'), ('MEETING_OR_NETWORKING_EVENT', 'Meeting or Networking Event'), ('PARTY_OR_SOCIAL_GATHERING', 'Party or Social Gathering'), ('RACE_OR_ENDURANCE_EVENT', 'Race or Endurance Event'), ('RALLY', 'Rally'), ('SCREENING', 'Screening'), ('SEMINAR_OR_TALK', 'Seminar or Talk'), ('TOUR', 'Tour'), ('TOURNAMENT', 'Tournament'), ('TRADE_SHOW_CONSUMER_SHOW_OR_EXPO', 'TradeS how, Consumer Show, or Expo'), ('OTHER', 'Other')], max_length=250)),
                ('organizer', models.CharField(max_length=250)),
                ('tags', models.ManyToManyField(related_name='tags', to='meetups.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'venue', 'event_type', 'organizer')},
            },
        ),
    ]
