# Generated by Django 2.2.5 on 2019-09-10 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='tags',
            field=models.ManyToManyField(related_name='meet_up_tags', to='meetups.Tag'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_ups', to=settings.AUTH_USER_MODEL),
        ),
    ]
