# Generated by Django 2.2.5 on 2019-10-01 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='meetup',
            name='status',
            field=models.CharField(choices=[('APPEARANCE_OR_SIGNING', 'Appearance or Signing'), ('ATTRACTION', 'Attraction'), ('CAMP_TRIP_RETREAT', 'Camp, Trip, or Retreat'), ('CLASS_TRAINING_WORKSHOP', 'Class, Training, or Workshop'), ('CONCERT_OR_PERFORMANCE', 'Concert or Performance'), ('CONFERENCE', 'Conference'), ('CONVENTION', 'Convention'), ('DINNER_OR_GALA', 'Dinner or Gala'), ('FESTIVAL_OR_FAIR', 'Festival or Fair'), ('GAME_OR_COMPETITION', 'Game or Competition'), ('MEETING_OR_NETWORKING_EVENT', 'Meeting or Networking Event'), ('PARTY_OR_SOCIAL_GATHERING', 'Party or Social Gathering'), ('RACE_OR_ENDURANCE_EVENT', 'Race or Endurance Event'), ('RALLY', 'Rally'), ('SCREENING', 'Screening'), ('SEMINAR_OR_TALK', 'Seminar or Talk'), ('TOUR', 'Tour'), ('TOURNAMENT', 'Tournament'), ('TRADE_SHOW_CONSUMER_SHOW_OR_EXPO', 'TradeS how, Consumer Show, or Expo'), ('OTHER', 'Other')], default='APPEARANCE_OR_SIGNING', max_length=250),
        ),
    ]
