# Generated by Django 2.2.5 on 2019-10-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='location',
            new_name='venue',
        ),
    ]
