# Generated by Django 2.2.5 on 2019-10-01 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20191001_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='status',
            new_name='event_type',
        ),
        migrations.AddField(
            model_name='meetup',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
    ]
