# Generated by Django 2.2.5 on 2019-10-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20191002_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together={('name', 'venue', 'event_type', 'organizer')},
        ),
    ]
