# Generated by Django 2.2.5 on 2019-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='meetups.Tag'),
        ),
    ]
