# Generated by Django 2.2.5 on 2019-09-25 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
    ]
